use_frameworks!

target 'Teller_Example' do
  pod 'Teller', :path => '../'
  pod 'RxCocoa', '~> 5.0'
  pod 'Moya/RxSwift', '~> 14.0.0-alpha.1'

  target 'Teller_Tests' do
    inherit! :search_paths

    pod 'RxBlocking', '~> 5.0'
    pod 'RxTest',     '~> 5.0'    
  end
end
