use_frameworks!

target 'Teller_Example' do
  pod 'Teller', :path => '../'

  target 'Teller_Tests' do
    inherit! :search_paths

    pod 'RxBlocking', '~> 4.3'
    pod 'RxTest',     '~> 4.3'    
  end
end
