os: osx
osx_image: xcode10.2
language: swift

before_cache:
  - cocoacache save --podfile Example/Podfile.lock 
cache:
  bundler: true 
  directories:    
    - Specs
install:  
  - bundle install
  - cocoacache restore --podfile Example/Podfile.lock
  - cd Example; pod install --repo-update; cd ..

jobs:
  include:
  - stage: tests
    script: ruby bin/run_unit_tests.rb

stages:
- name: tests
  if: type IN (pull_request, push) AND tag IS blank
