os: osx
osx_image: xcode10.1
language: swift
before_install:
- gem install cocoapods --pre # update cocoapods to newest version.
install:
- bundle install
- cd Teller/Example; bundle exec pod check || (bundle exec pod install --repo-update) # use () to group commands together to run if `pod check` returns false
cache:
  directories:
    - $HOME/.rvm/gems
    - $HOME/.cocoapods
jobs:
  include:
  - stage: pull-request
    script: ruby bin/run_unit_tests.rb
    
stages:
- name: pull-request
  if: type IN (pull_request) 
