os: osx
osx_image: xcode11.4
language: swift

cache:
  bundler: true 
  cocoapods: true
  
before_install:
  - gem install cocoapods
  - gem install fastlane # for running tests via scan   
  - pod --version
  - pod repo update
install:
  - bundle install
  - cd Example; pod install; cd ..;
env:
  global:
    # COCOAPODS_TRUNK_TOKEN - access token to deploy to cocoapods. 

jobs:
  include:
  - stage: commit 
    script:
      - fastlane scan
      - pod lib lint
  - stage: pr
    script:
      - pod lib lint
      - fastlane scan       
      - danger --fail-on-errors=true 
  - stage: deploy
    script: 
      - pod trunk push

stages:
  - name: commit
    if: type IN (push) AND tag IS blank
  - name: pr
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present